name: Metrics
on:
  # Run every Friday night
  schedule: [{ cron: "0 0 * * 5" }]
  # Run workflow manually
  workflow_dispatch:
jobs:
  Metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: General
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: GeneralInfo.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header
          base_indepth: yes
          template: classic
          config_order: base.header, isocalendar, languages
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css, tex
          plugin_languages_details: lines, byte-size, percentage
          plugin_languages_sections: most-used, recently-used
          plugin_languages_indepth: yes

      #      - name: Wakatime
      #        if: ${{ success() || failure() }}
      #        uses: lowlighter/metrics@latest
      #        with:
      #          filename: Wakatime.svg
      #          token: ${{ secrets.METRICS_TOKEN }}
      #          base: ""
      #          plugin_wakatime: yes
      #          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
      #          plugin_wakatime_url: https://wakatime.com/@AbdallahMehiz
      #          plugin_wakatime_user: AbdallahMehiz
      #          plugin_wakatime_sections: time, languages, editors, os
      #          plugin_wakatime_limit: 5
      #         plugin_wakatime_days: 7
      #          plugin_wakatime_repositories_visibility: public

      - name: Chess
        if: ${{ success() || failure() }}
        uses: lowlighter/metrics@latest
        with:
          filename: Chess.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_chess: yes
          plugin_chess_token: ${{ secrets.CHESS_TOKEN }}
          plugin_chess_user: AbdallahMehiz
          plugin_chess_platform: lichess.org
